### ISSUE TITLE
Thor LUKS encryption key stored on disk?

### ISSUE THREAD

**Issue by JoshAusHessen** [jnsgruk/nixos-config#31]
Hey, this is not really an issue, more of a [discussion](https://docs.github.com/en/discussions/quickstart), but since they are not enabled I post it here.

In the Thor config [`host/thor/disks.nix`](https://github.com/jnsgruk/nixos-config/blob/f973897b81c8505c2236fde5c93edfd31fa3c72c/host/thor/disks.nix) the 4TB data drive is configured with a LUKS encryption and the password to decrypt is stored in `/tmp`
```
content = {
  type = "luks";
  name = "data";

  settings = {
  # Make sure there is no trailing newline in keyfile if used for interactive unlock.
  #  Use `echo -n "password" > /tmp/secret.key`
  keyFile = "/tmp/data.keyfile";
  allowDiscards = true;
  };

  [...]
};
```

As I understand it the `/tmp` folder is stored on disk by default and only gets wiped on boot (I didn't see any changes to that in your configuration). 
So if a malicious actor could get access to your device, cut the power and then read the disk from a different system without booting Thor, they would have access to your decrypt key and therefore the data on the 4TB data drive.

I think the alternative would be to store the key in RAM so it gets wiped when the power is cut rather than on boot (and maybe disable the swap file?).
So either putting in the password manually on every reboot with a ssh connection.
Or configure `/tmp` to be stored in RAM rather than on disk.

What do you think? Did I miss something?

Besides that, awesome config :star2:  I love to copy-paste from it :heart_hands:

**Comment by jnsgruk** [comment]
Hey!

That key is read *at install time*. I use `disko` to partition the disks, and have written a small script to help with that.

The keyfile [is generated](https://github.com/jnsgruk/nixos-config/blob/48a8612ae76971346567c7c2e8b4d40ec7c8a3c6/scripts/install-with-disko#L27) just before the install, [then copied](https://github.com/jnsgruk/nixos-config/blob/48a8612ae76971346567c7c2e8b4d40ec7c8a3c6/scripts/install-with-disko#L55) to my root disk.

In my setup, I have a root disk, which is encrypted using a key stored in the TPM. Once that disk is unlocked, the key file in `/etc/...` is read to unlock the secondary disk on the machine. So the keyfile you see reference to is also encrypted, and only available once the machine's root disk has been unlocked/booted.

**Comment by JoshAusHessen** [comment]
Ah nice. More stuff to look into, Thanks!
